### PR TITLE
Search bar is working Now

### PR DESCRIPTION
**Pull request by RaheesAhmed**

### CODE REVIEW

**Comment by ShubhBaranwal** [comment]
it's not working

**Comment by RaheesAhmed** [comment]
I have check it test it and then created the pull request let me share screen shot here

**Comment by RaheesAhmed** [comment]
Capture
you can check its working on my side

**Comment by RaheesAhmed** [comment]
Capture

**Comment by ShubhBaranwal** [comment]
After typing product name project does not show

**Pull request merged**
